### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/eslint-config-near#1]
Can you please update the readme for how to install and use it?

I'm working in my own project and ran `yarn add -D eslint-config-near`, but it didn't seem to change the formatting of my files. 

Also, in the past, I've always seemed to need Prettier in addition to Eslint for immediate autoformatting in VSC.

If Prettier is not involved here, does autoformatting still work how I'm used to?

Thanks.

**Comment by petarvujovic98** [comment]
I'll update the usage section of the README. For now, you need both eslint and prettier installed, and a `.eslintrc.js` config that looks something like this:
```js
module.exports = {
  extends: ["near"]
};
```

**Comment by ryancwalsh** [comment]
@petarvujovic98  Thanks.

**Comment by ryancwalsh** [comment]
@petarvujovic98 Can you please let me know what I'm doing wrong here? 

https://github.com/NEARFoundation/trulioo-app/commit/659939fa6ab7de1ca1bf162b09bebcdf45908e95

I also created https://github.com/NEARFoundation/near-prettier-config and published to https://www.npmjs.com/package/@nearfoundation/near-prettier-config

I think all relevant NF projects should use (or at least start with as a basis) your Eslint config and this Prettier config. cc @sandoche

**Comment by petarvujovic98** [comment]
@ryancwalsh I see one problem in the `server` dir when I run `eslint` and that is that the file needs to be `.eslintrc.cjs` instead of `eslintrc.js`, notice the **c** in `.cjs`. This is because the project is configured as a module (e.g. in [`package.json` ](https://github.com/NEARFoundation/trulioo-app/blob/659939fa6ab7de1ca1bf162b09bebcdf45908e95/server/package.json#L6)), so when I changed the name of the file it did fix a lot of files, but there seems to be a lot of errors that need to be fixed manually.

As a side note I would suggest adding the following:
`.eslintrc.cjs`
```javascript
/* eslint-env node */

module.exports = {
  extends: ['near'], // See https://github.com/NEAR-Edu/eslint-config-near/blob/main/package.json
};
```
`package.json`
```json
{
  "scripts": {
    "lint": "eslint ./src --fix",
  }
}
```

And if you are using VSCode adding a auto lint setting like this:
`.vscode/settings.json`
```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
  "editor.formatOnSave": true
}
```
Or if using neovim there is [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) which can be configured to run eslint and prettier on save.

Hope this helps

**Comment by ryancwalsh** [comment]
@petarvujovic98 Thanks so much!
